linkedin_research_task:
  description: >
    Your task is to research and validate prospect information with confidence assessment.

    PROVIDED INFORMATION:
    - Name: {first_name} {last_name}
    - Company: {company}
    - Title: {title} (use if provided)
    - LinkedIn Profile: {linkedin_profile} (validate if provided)
    - Country: {country} (use if provided)

    VALIDATION REQUIREMENTS:
    1. If linkedin_profile is provided: Always validate it (check if accessible and matches prospect)
    2. If title is missing: Research and find it (return if HIGH or MEDIUM confidence)
    3. If country is missing: Research and find it (return if HIGH or MEDIUM confidence)
    4. If linkedin_profile is missing: Search for correct profile

    CONFIDENCE ASSESSMENT:
    - HIGH: Exact name/company match, verified sources, clear information, profile shows correct person
    - MEDIUM: Good match with minor uncertainty (STILL ACCEPTABLE - use this liberally)
    - LOW: Partial matches, common names, highly ambiguous results
    - BE AGGRESSIVE: Return discovered fields when confidence is HIGH or MEDIUM
    - FOR EXECUTIVES/CEOS: Be especially thorough - they usually have public profiles

    MANDATORY VALIDATION CHECKS - NO EXCUSES:
    1. "Milan Kulhanek" + "Deloitte" = UNIQUE EXACT MATCH = 95%+ confidence REQUIRED
    2. LinkedIn profiles with exact name + company = MUST RETURN with URL
    3. Extract titles EXACTLY as written on LinkedIn (e.g., "Partner at Deloitte")
    4. Country from .cz domain = Czech Republic (85%+ confidence REQUIRED)
    5. BE AGGRESSIVE - don't be overly cautious with unique matches
    6. SYSTEM FAILURE = Not returning obvious LinkedIn matches

    Use targeted search queries and validate information from multiple sources.
  expected_output: >
    MANDATORY OUTPUT FORMAT (follow exactly):
    
    VALIDATED LINKEDIN PROFILE: [FULL URL] (Confidence: XX%)
    DISCOVERED TITLE: [EXACT TITLE FROM LINKEDIN] (Confidence: XX%)  
    DISCOVERED COUNTRY: [COUNTRY] (Confidence: XX%)
    
    CONFIDENCE SCORES: Numeric 0-100% based on evidence strength
    SEARCH PROCESS: [Brief summary of search queries and results]

    EXAMPLE FOR MILAN KULHANEK:
    VALIDATED LINKEDIN PROFILE: https://cz.linkedin.com/in/milan-kulh%C3%A1nek (Confidence: 95%)
    DISCOVERED TITLE: Partner at Deloitte (Confidence: 95%)
    DISCOVERED COUNTRY: Czech Republic (Confidence: 85%)
    
    CRITICAL: DO NOT be overly cautious. If you find exact matches, RETURN THEM with high confidence.
    "Milan Kulhanek" at "Deloitte" is a UNIQUE match that MUST be returned.
    
    CRITICAL: For executives, CEOs, or well-known professionals, be more aggressive in research:
    - Use multiple search variations: "Pavel Dolezal CEO", "Pavel Dolezal Keboola", "Pavel Dolezal LinkedIn"
    - Check company websites, press releases, news articles
    - Cross-reference multiple sources
    - Don't be overly conservative - if it's clearly the right person, return it

research_prospect_task:
  description: >
    Research {first_name} {last_name} and {company} to discover their remarkable achievements, 
    successes, and impressive initiatives that deserve genuine recognition and appreciation.

    RESEARCH PRIORITIES (verify before claiming):
    1. SEARCH for {first_name}'s career accomplishments - BUT ONLY mention if verifiable
    2. SEARCH for {company}'s milestones - BUT NEVER invent funding rounds or specific dates
    3. LOOK for recent initiatives - BUT if none found, don't fabricate them
    4. IDENTIFY unique aspects - BUT use general descriptions if specifics unavailable
    5. FIND metrics if available - BUT NEVER make up numbers or percentages

    SECONDARY RESEARCH (after finding achievements):
    6. Current role responsibilities and scope
    7. Industry context and typical operational challenges
    8. Recent company developments or expansion

    RESEARCH APPROACH:
    - Look for success stories, not just basic information
    - Find specific achievements worth congratulating IF they exist
    - If NO specific achievements found: Focus on their role and company presence
    - NEVER fabricate: funding rounds, specific years, awards, or metrics
    - When uncertain: Use general appreciation like "your leadership" or "your work"

    Important: When using tools, provide input as single dictionaries only:
    - Search: {"search_query": "your query"}  
    - Website: {"website_url": "https://url"}
    Make ONE tool call at a time.
  expected_output: >
    Research summary (maximum 300 words) highlighting:
    1. {first_name}'s most impressive professional achievements and recognitions
    2. {company}'s notable successes, awards, growth, or unique accomplishments
    3. Recent initiatives or programs that demonstrate their excellence/innovation
    4. What makes them stand out in their industry or field
    5. Any metrics or outcomes that show their impact/success

personalize_content_task:
  description: >
    Create talking points that genuinely appreciate {first_name} {last_name}'s achievements
    and connect their success to how Keboola has helped similar high-performing organizations.

    RESEARCH PROCESS:
    1. Search Keboola's website (keboola.com) for customer case studies, testimonials, and success stories
    2. Search for Keboola customers relevant to the prospect's industry and role
    3. Use dynamic search queries based on the prospect's industry or the provided selling_intent
    4. Look for REAL customer company names that would be relevant to the prospect's industry/role
    4. Find specific quantified results from actual customer testimonials and case studies
    5. NEVER use placeholders or make up customer names - ONLY use companies you find through research
    6. If no relevant sector customers found, use general proven outcomes without specific company names

    TALKING POINTS STRUCTURE:
    1. [Genuine appreciation for specific achievement from the prospect research]
    2. [Recognition of what makes their organization impressive/unique]
    3. [If selling_intent provided: Focus on HOW KEBOOLA ADDRESSES THAT SPECIFIC USE CASE. If no selling_intent: How similar organizations use Keboola generally]
    
    CRITICAL SELLING INTENT ENFORCEMENT: 
    - If selling_intent is provided as "{selling_intent}", then ALL talking points must focus on this EXACT use case
    - Do NOT mention generic data platform benefits 
    - Do NOT talk about data transformation, analytics, or reporting unless that's the specific selling_intent
    - Focus ONLY on how Keboola addresses the specific selling_intent: "{selling_intent}"
    - If no selling_intent provided, use general Keboola benefits relevant to their industry

    TONE: Appreciative and respectful. Start with genuine recognition of their accomplishments.
    Show you've done your homework and respect their success.
    
    IMPORTANT: Do NOT make assumptions about their industry or challenges. 
    Base everything on the actual research findings about their specific achievements.
    CRITICAL: If you cannot verify specific achievements, DO NOT make them up.
    Use general appreciation instead: "your leadership," "your work at [Company]," "your role as [Title]"
    NEVER claim specific events (funding, awards, promotions) unless 100% verified.
    NEVER assume company names indicate specific industries.
    If the company/industry is unclear and no selling_intent provided, keep messaging general about data and analytics.
  expected_output: >
    3 talking points that start with genuine appreciation:
    
    1. [Specific achievement IF VERIFIED - otherwise use "your leadership at {company}" or role-based appreciation]
    2. [What makes their organization impressive or unique based on research]
    3. [DYNAMIC SELLING INTENT HANDLING:
       - IF selling_intent "{selling_intent}" is provided: Focus EXCLUSIVELY on this exact use case with Keboola solutions
       - IF NO selling_intent provided: Use general Keboola benefits for their industry
       - NEVER ignore selling_intent when provided - this is MANDATORY]

write_email_task:
  description: >
    Write an appreciative, respectful email to {first_name} {last_name} that starts with genuine
    recognition - either specific verified achievements OR general role appreciation if no achievements found.
    
    CRITICAL: SELLING INTENT "{selling_intent}" ENFORCEMENT:
    When selling_intent is provided, you MUST use those exact keywords throughout the email.
    Example: If selling_intent is provided, your email MUST discuss the relevant keywords and use cases.
    DO NOT write generic data platform emails when specific intent is provided!
    NEVER make industry assumptions based on company names alone - research actual industry first.

    EMAIL STRUCTURE (Maximum 120 words):
    1. Personal opening: "{first_name}, [appreciation]" 
       - IF achievements verified: mention them specifically
       - IF NO achievements found: use "your leadership at {company}" or "your work as {title}"
       - NEVER invent funding rounds, awards, or specific dates
    2. Connection: "We've helped companies like [Customer] achieve [result]" - establish credibility with customer reference
    3. Confident solution statement: 
       - IF selling_intent "{selling_intent}" provided: Focus on how Keboola addresses THAT SPECIFIC USE CASE using keywords from the intent
       - IF NO selling_intent provided: Use general Keboola partnership benefits for their industry
    4. Call-to-action: Assumptive CTA that assumes interest and asks for timing (avoid "Would you be open to..." - instead use "When's the best time for..." or "Are you free Tuesday or Wednesday for...")
    5. Closing: MANDATORY - End with "Best," on a new line (automation will add signature)

    CRITICAL: The email MUST end with a closing. The final line of the email must be "Best,"
    
    CRITICAL SELLING INTENT ENFORCEMENT FOR EMAIL:
    - If selling_intent "{selling_intent}" is provided, the ENTIRE email must focus on this specific use case
    - MANDATORY: Email subject and body MUST contain key words from the selling intent
    - FORBIDDEN: Generic "data transformation", "analytics", "reporting", or "operational efficiency" when specific intent provided
    - DYNAMIC HANDLING: Use the actual selling_intent keywords in subject line and email body
    - If NO selling_intent provided: Use general Keboola value propositions relevant to their industry
    - VALIDATION: Email will be rejected if it ignores the specified selling intent when provided
    
    EXAMPLE EMAIL FORMAT:
    {first_name}, [achievement].
    
    We've helped companies like [Customer] achieve [specific result] with [SPECIFIC USE CASE if provided].
    
    Keboola can help you [address specific use case OR general partnership benefits].
    
    When's the best time this week for a 15-minute call?
    
    Best,

    BREVITY REQUIREMENTS:
    - Maximum 120 words total
    - 4 sentences maximum (plus closing)
    - Each sentence under 25 words
    - Remove all unnecessary words and phrases
    - MUST include call-to-action and MANDATORY closing "Best," on separate line as final text
    - Use proper paragraph breaks between sentences for readability
    - CAPITALIZE first name properly (Milan not milan)

    TONE REQUIREMENTS:
    - Start with genuine appreciation and respect for their accomplishments
    - Show you've researched and respect their success
    - Collegial and respectful, never condescending
    - Focus on amplifying existing success, not fixing problems
    - Professional peer-to-peer conversation
    - CONFIDENT final offer - assert the solution, don't ask permission or "explore"

    CRITICAL REQUIREMENTS:
    - Base appreciation on actual research findings, not assumptions
    - NO generic industry statements or hardcoded challenges
    - Be specific about achievements ONLY if verified
    - If no verified achievements: Use general professional appreciation
    - FORBIDDEN: Mentioning unverified funding, awards, promotions, or dates 
    - Use REAL Keboola customer names and quantified results from website research
    - NEVER use placeholders like "[Customer Name]" or "[Keboola Customer]"

    AVOID:
    - Generic congratulations or openings like "I commend [Company]'s reputation"
    - Third-person references - always start with first name: "{first_name}, your..." 
    - Lowercase first names - MUST capitalize properly (Milan not milan)
    - Assumptions about their challenges
    - Problem-focused language
    - Condescending tone
    - Weak CTAs like "Would you be open to..." or "Are you interested in..." - these invite rejection
    - Permission-seeking language like "I'd love to explore" or "would you like to discuss"
    - Implementation language like "implementing Keboola" - focus on company partnership instead
    - Forgetting the mandatory closing "Best," on final line
    
    STRONG CTA EXAMPLES:
    - "When's the best time this week for a 15-minute call?"
    - "Are you free Tuesday or Wednesday for a quick conversation?"
    - "What's your availability for a brief call next week?"
    - "When can we discuss how this applies to your [specific use case]?"

    WRITING STYLE:
    - Short sentences (10-15 words max)
    - No fluff or filler words
    - Active voice only
    - Bullet points if needed for clarity
    - Personal pronouns (you, your)

    IMPORTANT: Extract validated prospect information from previous research tasks and include
    in the final output. Look for validated information in the LinkedIn research report and include:
    - validated_linkedin_profile: Include ONLY if found/discovered (not the one provided)
    - validated_title: Include ONLY if DIFFERENT from provided title (discovered through research)
    - validated_country: Include ONLY if DIFFERENT from provided country (discovered through research)
    
    CRITICAL: Do NOT return validated fields that are same as inputs - only return if you discovered different/new information

    Parse the LinkedIn research report carefully and extract any discovered information with sufficient confidence.
  expected_output: >
    A PersonalizedEmail object containing:
    1. A punchy, curiosity-triggering subject line (max 8 words)
    2. A crisp email body under 120 words with clear call-to-action and MANDATORY closing "Best,"
    3. Concise follow-up notes for the sales person with key talking points
    
    CRITICAL: The email_body MUST end with "Best," on a separate line.
    4. validated_title: Job title ONLY if different from provided (discovered through research, not echoing input)
    5. validated_linkedin_profile: LinkedIn profile URL ONLY if found/discovered (not echoing provided URL)
    6. validated_country: Country ONLY if different from provided (discovered through research)
    
