linkedin_research_task:
  description: >
    Your task is to research and validate prospect information with confidence assessment.

    PROVIDED INFORMATION:
    - Name: {first_name} {last_name}
    - Company: {company}
    - Title: {title} (use if provided)
    - LinkedIn Profile: {linkedin_profile} (validate if provided)
    - Country: {country} (use if provided)

    VALIDATION REQUIREMENTS:
    1. If linkedin_profile is provided: Always validate it (check if accessible and matches prospect)
    2. If title is missing: Research and find it (only return if HIGH confidence)
    3. If country is missing: Research and find it (only return if HIGH confidence)
    4. If linkedin_profile is missing: Search for correct profile

    CONFIDENCE ASSESSMENT:
    - HIGH: Exact name/company match, verified sources, clear information
    - LOW: Partial matches, common names, ambiguous results
    - Only return discovered fields when confidence is HIGH

    Use targeted search queries and validate information from multiple sources.
  expected_output: >
    A report containing:
    1. Validated LinkedIn profile URL (if found/validated)
    2. Confidence assessment for each piece of information
    3. Only include title and country if confidence is HIGH
    4. Clear statement of what was validated vs. what was discovered

research_prospect_task:
  description: >
    Conduct thorough research on {first_name} {last_name}, their role as
    {title} at {company}, and the company itself.
    Use the validated LinkedIn profile from the previous task and other publicly
    available sources to gather comprehensive information.

    Research areas to focus on:
    1. Professional background and career progression
    2. Company information, industry, and recent news
    3. Professional interests, achievements, and challenges
    4. Industry trends and pain points relevant to their role
    5. Company's data/technology initiatives (if any)

    Important: When using tools, provide input as single dictionaries only:
    - Search: {"search_query": "your query"}
    - Website: {"website_url": "https://url"}
    Make ONE tool call at a time.
  expected_output: >
    A comprehensive dossier on {first_name} {last_name} and {company},
    including recent professional activities, potential pain points, interests,
    industry challenges, and any other information that could be used to
    personalize communication about Keboola's data platform.

personalize_content_task:
  description: >
    Using the research on {first_name} {last_name} and {company},
    identify specific ways that Keboola's unified data & AI orchestration platform
    can address their potential needs or align with their professional interests.

    Consider:
    1. If selling_intent is provided: "{selling_intent}", use this as primary guidance
    2. If no selling_intent: Create relevant Keboola use cases based on their industry, role, and company needs
    3. Keboola's key benefits: 4x productivity boost, 73% faster project delivery, 80% less maintenance
    4. 700+ connectors, AI-powered automation, enterprise governance
    5. Industry-specific pain points that Keboola can solve

    Look for unique angles or shared points of interest that can create
    a strong personal connection in the email.
  expected_output: >
    A list of personalized talking points and angles to use in the email,
    connecting {first_name} {last_name}'s background, interests, or challenges
    with specific benefits of Keboola's data platform. Include specific features,
    use cases, and value propositions most relevant to their situation.

write_email_task:
  description: >
    Craft a highly personalized email to {first_name} {last_name} about Keboola's
    data and AI orchestration platform. Use the research and personalized content
    to create an email that feels individual, relevant, and engaging.

    The email should:
    1. Demonstrate understanding of their role and challenges
    2. Showcase how Keboola can provide specific value to their situation
    3. Reference validated prospect information from research
    4. Include relevant industry insights
    5. Have a clear call-to-action for further conversation
    6. Maintain a professional yet personable tone

    IMPORTANT: Extract validated prospect information from previous research tasks and include
    in the final output. Only include fields where confidence was assessed as HIGH.
  expected_output: >
    A PersonalizedEmail object containing:
    1. A compelling, personalized subject line (max 10 words, trigger curiosity)
    2. The body of the email, written in a conversational yet professional tone
    3. Follow-up notes for the sales person with specific talking points for future interactions
    4. validated_title: Job title (only if HIGH confidence from research)
    5. validated_linkedin_profile: LinkedIn profile URL (if found/validated)
    6. validated_country: Country location (only if HIGH confidence from research)
    
