linkedin_research_task:
  description: >
    Your task is to research and validate prospect information with confidence assessment.

    PROVIDED INFORMATION:
    - Name: {first_name} {last_name}
    - Company: {company}
    - Title: {title} (use if provided)
    - LinkedIn Profile: {linkedin_profile} (validate if provided)
    - Country: {country} (use if provided)

    VALIDATION REQUIREMENTS:
    1. If linkedin_profile is provided: Always validate it (check if accessible and matches prospect)
    2. If title is missing: Research and find it (return if HIGH or MEDIUM confidence)
    3. If country is missing: Research and find it (return if HIGH or MEDIUM confidence)
    4. If linkedin_profile is missing: Search for correct profile

    CONFIDENCE ASSESSMENT:
    - HIGH: Exact name/company match, verified sources, clear information, profile shows correct person
    - MEDIUM: Good match with minor uncertainty (STILL ACCEPTABLE - use this liberally)
    - LOW: Partial matches, common names, highly ambiguous results
    - BE AGGRESSIVE: Return discovered fields when confidence is HIGH or MEDIUM
    - FOR EXECUTIVES/CEOS: Be especially thorough - they usually have public profiles

    Use targeted search queries and validate information from multiple sources.
  expected_output: >
    A detailed report containing:
    1. VALIDATED LINKEDIN PROFILE: [URL] (return if found and confidence is HIGH/MEDIUM)
    2. DISCOVERED TITLE: [title] (if confidence is HIGH or MEDIUM)
    3. DISCOVERED COUNTRY: [country] (if confidence is HIGH or MEDIUM)
    4. CONFIDENCE LEVELS: State confidence (HIGH/MEDIUM/LOW) for each field
    5. SEARCH PROCESS: Brief summary of search queries used and results found

    FORMAT EXAMPLE:
    - LinkedIn Profile: https://linkedin.com/in/person-name (CONFIDENCE: HIGH - exact match)
    - Title: Chief Technology Officer (CONFIDENCE: HIGH - clearly stated on profile)
    - Country: United States (CONFIDENCE: HIGH - confirmed from profile location)

    Be thorough in your search and don't be overly cautious - return LinkedIn profiles if they clearly match the person.
    
    CRITICAL: For executives, CEOs, or well-known professionals, be more aggressive in research:
    - Use multiple search variations: "Pavel Dolezal CEO", "Pavel Dolezal Keboola", "Pavel Dolezal LinkedIn"
    - Check company websites, press releases, news articles
    - Cross-reference multiple sources
    - Don't be overly conservative - if it's clearly the right person, return it

research_prospect_task:
  description: >
    Research {first_name} {last_name} and {company} to discover their remarkable achievements, 
    successes, and impressive initiatives that deserve genuine recognition and appreciation.

    RESEARCH PRIORITIES (find achievements first):
    1. {first_name}'s notable career accomplishments, awards, recognitions, or leadership achievements
    2. {company}'s impressive results, growth milestones, awards, or industry recognition
    3. Recent initiatives, programs, or innovations they've launched that show excellence
    4. Unique aspects of their organization that set them apart from peers
    5. Any impressive metrics, outcomes, or impact they've achieved

    SECONDARY RESEARCH (after finding achievements):
    6. Current role responsibilities and scope
    7. Industry context and typical operational challenges
    8. Recent company developments or expansion

    RESEARCH APPROACH:
    - Look for success stories, not just basic information
    - Find specific achievements worth congratulating
    - Identify what makes them/their organization special
    - Focus on positive accomplishments and innovations

    Important: When using tools, provide input as single dictionaries only:
    - Search: {"search_query": "your query"}  
    - Website: {"website_url": "https://url"}
    Make ONE tool call at a time.
  expected_output: >
    Research summary (maximum 300 words) highlighting:
    1. {first_name}'s most impressive professional achievements and recognitions
    2. {company}'s notable successes, awards, growth, or unique accomplishments
    3. Recent initiatives or programs that demonstrate their excellence/innovation
    4. What makes them stand out in their industry or field
    5. Any metrics or outcomes that show their impact/success

personalize_content_task:
  description: >
    Create talking points that genuinely appreciate {first_name} {last_name}'s achievements
    and connect their success to how Keboola has helped similar high-performing organizations.

    RESEARCH PROCESS:
    1. Search Keboola's website (keboola.com) for customer case studies, testimonials, and success stories
    2. SEARCH SPECIFICALLY for Keboola customers in education, schools, universities, or non-profit sectors 
    3. Use search queries like "keboola education customer case study" or "keboola school university"
    4. Look for REAL customer company names that would be relevant to the prospect's industry/role
    4. Find specific quantified results from actual customer testimonials and case studies
    5. NEVER use placeholders or make up customer names - ONLY use companies you find through research
    6. If no relevant sector customers found, use general proven outcomes without specific company names

    TALKING POINTS STRUCTURE:
    1. [Genuine appreciation for specific achievement from the prospect research]
    2. [Recognition of what makes their organization impressive/unique]
    3. [If selling_intent provided: Focus on HOW KEBOOLA ADDRESSES THAT SPECIFIC USE CASE. If no selling_intent: How similar organizations use Keboola generally]
    
    CRITICAL SELLING INTENT ENFORCEMENT: 
    - If selling_intent is provided as "{selling_intent}", then ALL talking points must focus on this EXACT use case
    - Do NOT mention generic data platform benefits 
    - Do NOT talk about data transformation, analytics, or reporting unless that's the specific selling_intent
    - Focus ONLY on how Keboola addresses the specific selling_intent: "{selling_intent}"
    - Example: If selling_intent is "coffee machine", talk about coffee-related data, not financial data

    TONE: Appreciative and respectful. Start with genuine recognition of their accomplishments.
    Show you've done your homework and respect their success.
    
    IMPORTANT: Do NOT make assumptions about their industry or challenges. 
    Base everything on the actual research findings about their specific achievements.
  expected_output: >
    3 talking points that start with genuine appreciation:
    
    1. [Specific achievement or success worthy of recognition - be genuine and specific]
    2. [What makes their organization impressive or unique based on research]
    3. [If selling_intent provided: How Keboola solves THAT SPECIFIC USE CASE with examples. If no selling_intent: How relevant organizations use Keboola generally. NEVER ignore the selling_intent if provided.]

write_email_task:
  description: >
    Write an appreciative, respectful email to {first_name} {last_name} that starts with genuine
    recognition of their specific achievements before sharing how Keboola helps similar successful organizations.

    EMAIL STRUCTURE (Maximum 120 words):
    1. Personal opening: "{first_name}, [specific appreciation]" (CAPITALIZE first name properly, be authentic but brief)
    2. Connection: "We've helped companies like [Customer] achieve [result]" - establish credibility with customer reference
    3. Confident solution statement: If selling_intent provided, focus on how Keboola addresses THAT SPECIFIC USE CASE. If no selling_intent, general partnership benefits.
    4. Call-to-action: Direct ask for a brief call/meeting (one sentence, confident)
    5. Closing: MANDATORY - End with "Best," on a new line (automation will add signature)

    CRITICAL: The email MUST end with a closing. The final line of the email must be "Best,"
    
    CRITICAL SELLING INTENT ENFORCEMENT FOR EMAIL:
    - If selling_intent "{selling_intent}" is provided, the ENTIRE email must focus on this specific use case
    - Do NOT mention generic "data transformation", "analytics", "reporting", or "operational efficiency" 
    - Talk specifically about "{selling_intent}" and how Keboola helps with that exact use case
    - Example: If selling_intent is "coffee machine", discuss coffee machine operations, maintenance data, supply chain for coffee, etc.
    
    EXAMPLE EMAIL FORMAT:
    {first_name}, [achievement].
    
    We've helped companies like [Customer] achieve [specific result] with [SPECIFIC USE CASE if provided].
    
    Keboola can help you [address specific use case OR general partnership benefits].
    
    [CTA question]?
    
    Best,

    BREVITY REQUIREMENTS:
    - Maximum 120 words total
    - 4 sentences maximum (plus closing)
    - Each sentence under 25 words
    - Remove all unnecessary words and phrases
    - MUST include call-to-action and MANDATORY closing "Best," on separate line as final text
    - Use proper paragraph breaks between sentences for readability
    - CAPITALIZE first name properly (Milan not milan)

    TONE REQUIREMENTS:
    - Start with genuine appreciation and respect for their accomplishments
    - Show you've researched and respect their success
    - Collegial and respectful, never condescending
    - Focus on amplifying existing success, not fixing problems
    - Professional peer-to-peer conversation
    - CONFIDENT final offer - assert the solution, don't ask permission or "explore"

    CRITICAL REQUIREMENTS:
    - Base appreciation on actual research findings, not assumptions
    - NO generic industry statements or hardcoded challenges
    - Be specific about their achievements 
    - Use REAL Keboola customer names and quantified results from website research
    - NEVER use placeholders like "[Customer Name]" or "[Keboola Customer]"

    AVOID:
    - Generic congratulations or openings like "I commend [Company]'s reputation"
    - Third-person references - always start with first name: "{first_name}, your..." 
    - Lowercase first names - MUST capitalize properly (Milan not milan)
    - Assumptions about their challenges
    - Problem-focused language
    - Condescending tone
    - Weak language like "I'd love to explore" or "would you like to discuss" 
    - Implementation language like "implementing Keboola" - focus on company partnership instead
    - Asking permission - be confident in your solution offering
    - Forgetting the mandatory closing "Best," on final line

    WRITING STYLE:
    - Short sentences (10-15 words max)
    - No fluff or filler words
    - Active voice only
    - Bullet points if needed for clarity
    - Personal pronouns (you, your)

    IMPORTANT: Extract validated prospect information from previous research tasks and include
    in the final output. Look for validated information in the LinkedIn research report and include:
    - validated_linkedin_profile: Include if found (HIGH or MEDIUM confidence)
    - validated_title: Include if found with HIGH confidence
    - validated_country: Include if found with HIGH confidence

    Parse the LinkedIn research report carefully and extract any discovered information with sufficient confidence.
  expected_output: >
    A PersonalizedEmail object containing:
    1. A punchy, curiosity-triggering subject line (max 8 words)
    2. A crisp email body under 120 words with clear call-to-action and MANDATORY closing "Best,"
    3. Concise follow-up notes for the sales person with key talking points
    
    CRITICAL: The email_body MUST end with "Best," on a separate line.
    4. validated_title: Job title (only if HIGH confidence from research)
    5. validated_linkedin_profile: LinkedIn profile URL (if found/validated)
    6. validated_country: Country location (only if HIGH confidence from research)
    
